CREATE TABLE MESSAGE_TBL (
  CODE VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'メッセージコード',
  TYPE VARCHAR(5) NOT NULL COMMENT 'メッセージ種別',
  MESSAGE VARCHAR(512) COMMENT 'メッセージ',
  `登録日` DATETIME COMMENT '登録日',
  `更新日` DATETIME COMMENT '更新日',
  `論理削除フラグ` TINYINT(1) DEFAULT 0 COMMENT '論理削除フラグ',
  CONSTRAINT `メッセージ種別制約` CHECK(TYPE IN ('INFO', 'ERROR', 'WARN')),
  CONSTRAINT `論理削除フラグ制約` CHECK(`論理削除フラグ` IN (0, 1)) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='メッセージテーブル';
